import React, { useState, useMemo, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { applyToolSeo } from "../utils/seoUtils";
import { ToolLanguageSwitcher } from "./ToolLanguageSwitcher";
import {
  Calculator,
  Calendar,
  ArrowRight,
  Copy,
  Check,
  ShieldCheck,
  AlertCircle,
  Clock,
  RefreshCw,
  Sparkles,
} from "lucide-react";

interface CustomerLifetimeValueCalculatorPageProps {
  onOpenBooking: () => void;
  lang?: "de" | "en";
}

export const CustomerLifetimeValueCalculatorPage: React.FC<CustomerLifetimeValueCalculatorPageProps> = ({
  onOpenBooking,
  lang: propLang,
}) => {
  const location = useLocation();
  const currentLang: "de" | "en" = propLang || (location.pathname.startsWith("/en") ? "en" : "de");

  useEffect(() => {
    applyToolSeo("clv", currentLang);
    window.scrollTo(0, 0);
  }, [currentLang]);

  // Simple Inputs (all per 1 customer)
  const [aov, setAov] = useState<number>(68); // Average Order Value in €
  const [purchaseFrequency, setPurchaseFrequency] = useState<number>(2.4); // Purchases per year
  const [customerLifespan, setCustomerLifespan] = useState<number>(2.5); // Years
  const [grossMarginPercent, setGrossMarginPercent] = useState<number>(55); // Profit margin in %
  const [cac, setCac] = useState<number>(26); // Customer Acquisition Cost in €
  const [copied, setCopied] = useState<boolean>(false);

  // Preset scenarios
  const applyPreset = (
    presetAov: number,
    presetFreq: number,
    presetSpan: number,
    presetMargin: number,
    presetCac: number
  ) => {
    setAov(presetAov);
    setPurchaseFrequency(presetFreq);
    setCustomerLifespan(presetSpan);
    setGrossMarginPercent(presetMargin);
    setCac(presetCac);
  };

  // Calculations (clean & per single customer)
  const results = useMemo(() => {
    const effectiveSpan = Math.max(0.1, customerLifespan);
    const totalOrders = purchaseFrequency * effectiveSpan;
    const lifetimeRevenue = aov * totalOrders;
    // CLV is the gross profit / contribution margin generated by 1 customer
    const clv = lifetimeRevenue * (grossMarginPercent / 100);
    const netProfitPerCustomer = clv - cac;

    // Order 1 & Payback calculations
    const profitPerOrder = aov * (grossMarginPercent / 100);
    const ordersToBreakEven = profitPerOrder > 0 ? Math.ceil(cac / profitPerOrder) : 1;
    const isFirstOrderProfitable = profitPerOrder >= cac;
    const monthsBetweenOrders = purchaseFrequency > 0 ? 12 / purchaseFrequency : 12;
    const paybackMonths =
      ordersToBreakEven <= 1
        ? 0
        : Math.round((ordersToBreakEven - 1) * monthsBetweenOrders * 10) / 10;

    // Progression over years
    const maxYears = Math.max(3, Math.ceil(effectiveSpan));
    const yearlyBreakdown = Array.from({ length: Math.min(5, maxYears) }, (_, i) => i + 1).map(
      (year) => {
        const activeYears = Math.min(year, effectiveSpan);
        const orders = purchaseFrequency * activeYears;
        const revenue = orders * aov;
        const grossProfit = revenue * (grossMarginPercent / 100);
        const netProfit = grossProfit - cac;
        return {
          year,
          orders: Math.round(orders * 10) / 10,
          revenue: Math.round(revenue),
          grossProfit: Math.round(grossProfit),
          netProfit: Math.round(netProfit),
        };
      }
    );

    return {
      totalOrders,
      lifetimeRevenue,
      clv,
      netProfitPerCustomer,
      profitPerOrder,
      ordersToBreakEven,
      isFirstOrderProfitable,
      paybackMonths,
      yearlyBreakdown,
    };
  }, [aov, purchaseFrequency, customerLifespan, grossMarginPercent, cac]);

  const handleCopySummary = () => {
    const text = `Procware CLV Berechnung:
• Customer Lifetime Value (CLV): ${results.clv.toFixed(2)} €
• Gesamtumsatz pro Kunde: ${results.lifetimeRevenue.toFixed(2)} €
• Reingewinn nach CAC: ${results.netProfitPerCustomer.toFixed(2)} €
• Bestellungen Lebenszeit: ${results.totalOrders.toFixed(1)}x
---
Eingaben:
• Warenkorb (AOV): ${aov} €
• Kaufhäufigkeit: ${purchaseFrequency}x / Jahr
• Lebensdauer: ${customerLifespan} Jahre
• Bruttomarge: ${grossMarginPercent}%
• Akquisekosten (CAC): ${cac} €
Berechnet mit https://procware.io/customer-lifetime-value-calculator`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="pt-24 pb-20 bg-white min-h-screen">
      {/* Hero Section */}
      <section className="bg-slate-50 border-b border-slate-200 py-12 sm:py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Top utility row with Breadcrumb and discreet Top-Right Language Switcher */}
          <div className="flex items-center justify-between gap-4 mb-6">
            <Link
              to="/tools"
              className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-blue-600 transition-colors"
            >
              <span>←</span>
              <span>{currentLang === "en" ? "All E-Com Tools" : "Alle Tools"}</span>
            </Link>
            <div className="flex items-center gap-2">
              <ToolLanguageSwitcher toolKey="clv" currentLang={currentLang} />
            </div>
          </div>

          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-200 text-blue-700 text-xs font-bold uppercase tracking-wider mb-4">
            <Calculator className="w-3.5 h-3.5 text-blue-600" />
            <span>{currentLang === "en" ? "Shopify E-Commerce Calculator" : "Shopify E-Commerce Rechner"}</span>
          </div>
          <div className="max-w-3xl">
            <h1 className="text-3xl sm:text-5xl font-black text-slate-950 tracking-tight leading-tight">
              Customer Lifetime Value <span className="text-blue-600">Calculator</span>
            </h1>
            <p className="mt-4 text-base sm:text-lg text-slate-600 font-normal leading-relaxed">
              {currentLang === "en"
                ? "Calculate total customer value, profit per customer over their lifespan, and find how much you can afford to spend on customer acquisition (CAC)."
                : "Berechne einfach und transparent, wie viel ein Kunde über seine gesamte Lebensdauer wert ist und wie viel Gewinn dir nach Abzug der Werbekosten (CAC) übrig bleibt."}
            </p>

            {/* Quick Presets */}
            <div className="mt-6 flex flex-wrap items-center gap-2">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mr-1">
                Beispiel-Branchen:
              </span>
              <button
                onClick={() => applyPreset(65, 2.4, 2.5, 55, 26)}
                className="px-3 py-1.5 rounded-xl bg-white border border-slate-200 text-slate-700 text-xs font-semibold hover:border-slate-900 transition-colors cursor-pointer"
              >
                Fashion & Apparel
              </button>
              <button
                onClick={() => applyPreset(48, 3.5, 3.0, 68, 22)}
                className="px-3 py-1.5 rounded-xl bg-white border border-slate-200 text-slate-700 text-xs font-semibold hover:border-slate-900 transition-colors cursor-pointer"
              >
                Supplements & Beauty
              </button>
              <button
                onClick={() => applyPreset(145, 1.2, 1.8, 48, 42)}
                className="px-3 py-1.5 rounded-xl bg-white border border-slate-200 text-slate-700 text-xs font-semibold hover:border-slate-900 transition-colors cursor-pointer"
              >
                Home & Living
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Main Interactive Tool */}
      <section className="py-8 sm:py-12 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 sm:gap-8 items-start">
          {/* Left Column: Essential Parameter Inputs */}
          <div className="lg:col-span-6 bg-white border border-slate-200 rounded-3xl p-5 sm:p-8 shadow-xs">
            <h2 className="text-lg sm:text-xl font-black text-slate-950 flex items-center justify-between mb-6 pb-4 border-b border-slate-100">
              <span>Eingabedaten (pro Kunde)</span>
              <button
                onClick={() => applyPreset(68, 2.4, 2.5, 55, 26)}
                className="text-xs font-semibold text-slate-500 hover:text-slate-900 flex items-center gap-1 cursor-pointer py-1 px-2 rounded-lg hover:bg-slate-50"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Zurücksetzen</span>
              </button>
            </h2>

            <div className="space-y-6">
              {/* 1. AOV */}
              <div>
                <div className="flex flex-wrap justify-between items-center gap-2 mb-2">
                  <label htmlFor="clv-aov-input" className="text-xs sm:text-sm font-bold text-slate-900">
                    Durchschnittlicher Warenkorb (AOV)
                  </label>
                  <div className="flex items-center gap-1.5 bg-blue-50 px-2 py-1 rounded-xl border border-blue-200">
                    <input
                      id="clv-aov-input"
                      type="number"
                      step="0.01"
                      min="1"
                      value={aov}
                      onChange={(e) => setAov(Math.max(0, Number(e.target.value)))}
                      className="w-16 sm:w-20 bg-transparent text-right text-xs sm:text-sm font-extrabold text-blue-700 outline-none"
                    />
                    <span className="text-xs font-bold text-blue-600">€</span>
                  </div>
                </div>
                <input
                  type="range"
                  min="15"
                  max="400"
                  step="1"
                  value={Math.min(400, Math.max(15, aov))}
                  onChange={(e) => setAov(Number(e.target.value))}
                  className="w-full h-2 bg-slate-100 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
                <div className="flex justify-between text-[10px] sm:text-[11px] text-slate-400 mt-1">
                  <span>15 €</span>
                  <span>150 €</span>
                  <span>400 €+ (Freie Eingabe oben)</span>
                </div>
              </div>

              {/* 2. Purchase Frequency */}
              <div>
                <div className="flex flex-wrap justify-between items-center gap-2 mb-2">
                  <label htmlFor="clv-freq-input" className="text-xs sm:text-sm font-bold text-slate-900">
                    Kaufhäufigkeit pro Jahr
                  </label>
                  <div className="flex items-center gap-1.5 bg-blue-50 px-2 py-1 rounded-xl border border-blue-200">
                    <input
                      id="clv-freq-input"
                      type="number"
                      step="0.1"
                      min="0.1"
                      value={purchaseFrequency}
                      onChange={(e) => setPurchaseFrequency(Math.max(0.1, Number(e.target.value)))}
                      className="w-14 sm:w-16 bg-transparent text-right text-xs sm:text-sm font-extrabold text-blue-700 outline-none"
                    />
                    <span className="text-xs font-bold text-blue-600">x / Jahr</span>
                  </div>
                </div>
                <input
                  type="range"
                  min="1.0"
                  max="8.0"
                  step="0.1"
                  value={Math.min(8, Math.max(1, purchaseFrequency))}
                  onChange={(e) => setPurchaseFrequency(Number(e.target.value))}
                  className="w-full h-2 bg-slate-100 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
                <div className="flex justify-between text-[10px] sm:text-[11px] text-slate-400 mt-1">
                  <span>1x (Einmalig)</span>
                  <span>2.5x (Wiederkäufer)</span>
                  <span>8x+ (Sehr aktiv)</span>
                </div>
              </div>

              {/* 3. Customer Lifespan */}
              <div>
                <div className="flex flex-wrap justify-between items-center gap-2 mb-2">
                  <label htmlFor="clv-lifespan-input" className="text-xs sm:text-sm font-bold text-slate-900">
                    Kundenlebensdauer (Jahre)
                  </label>
                  <div className="flex items-center gap-1.5 bg-blue-50 px-2 py-1 rounded-xl border border-blue-200">
                    <input
                      id="clv-lifespan-input"
                      type="number"
                      step="0.1"
                      min="0.1"
                      value={customerLifespan}
                      onChange={(e) => setCustomerLifespan(Math.max(0.1, Number(e.target.value)))}
                      className="w-14 sm:w-16 bg-transparent text-right text-xs sm:text-sm font-extrabold text-blue-700 outline-none"
                    />
                    <span className="text-xs font-bold text-blue-600">Jahre</span>
                  </div>
                </div>
                <input
                  type="range"
                  min="0.5"
                  max="6.0"
                  step="0.1"
                  value={Math.min(6, Math.max(0.5, customerLifespan))}
                  onChange={(e) => setCustomerLifespan(Number(e.target.value))}
                  className="w-full h-2 bg-slate-100 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
                <div className="flex justify-between text-[10px] sm:text-[11px] text-slate-400 mt-1">
                  <span>0.5 Jahre</span>
                  <span>2.5 Jahre (Typischer Schnitt)</span>
                  <span>6+ Jahre</span>
                </div>
              </div>

              {/* 4. Gross Margin % */}
              <div>
                <div className="flex flex-wrap justify-between items-center gap-2 mb-2">
                  <label htmlFor="clv-margin-input" className="text-xs sm:text-sm font-bold text-slate-900">
                    Bruttomarge / Deckungsbeitrag (%)
                  </label>
                  <div className="flex items-center gap-1.5 bg-blue-50 px-2 py-1 rounded-xl border border-blue-200">
                    <input
                      id="clv-margin-input"
                      type="number"
                      step="0.5"
                      min="1"
                      max="99"
                      value={grossMarginPercent}
                      onChange={(e) =>
                        setGrossMarginPercent(Math.max(1, Math.min(99.9, Number(e.target.value))))
                      }
                      className="w-14 sm:w-16 bg-transparent text-right text-xs sm:text-sm font-extrabold text-blue-700 outline-none"
                    />
                    <span className="text-xs font-bold text-blue-600">%</span>
                  </div>
                </div>
                <input
                  type="range"
                  min="15"
                  max="85"
                  step="0.5"
                  value={Math.min(85, Math.max(15, grossMarginPercent))}
                  onChange={(e) => setGrossMarginPercent(Number(e.target.value))}
                  className="w-full h-2 bg-slate-100 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
                <p className="text-[11px] sm:text-xs text-slate-500 mt-1">
                  Dein Ertrag nach direkten Produkt- und Versandkosten.
                </p>
              </div>

              {/* 5. CAC */}
              <div>
                <div className="flex flex-wrap justify-between items-center gap-2 mb-2">
                  <label htmlFor="clv-cac-input" className="text-xs sm:text-sm font-bold text-slate-900">
                    Werbekosten pro Neukunde (CAC in €)
                  </label>
                  <div className="flex items-center gap-1.5 bg-blue-50 px-2 py-1 rounded-xl border border-blue-200">
                    <input
                      id="clv-cac-input"
                      type="number"
                      step="0.5"
                      min="0"
                      value={cac}
                      onChange={(e) => setCac(Math.max(0, Number(e.target.value)))}
                      className="w-16 sm:w-20 bg-transparent text-right text-xs sm:text-sm font-extrabold text-blue-700 outline-none"
                    />
                    <span className="text-xs font-bold text-blue-600">€</span>
                  </div>
                </div>
                <input
                  type="range"
                  min="0"
                  max="100"
                  step="1"
                  value={Math.min(100, Math.max(0, cac))}
                  onChange={(e) => setCac(Number(e.target.value))}
                  className="w-full h-2 bg-slate-100 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
                <p className="text-[11px] sm:text-xs text-slate-500 mt-1">
                  Was du im Schnitt an Ads (Meta, Google, TikTok) bezahlst, um 1 neuen Käufer zu gewinnen.
                </p>
              </div>
            </div>
          </div>

          {/* Right Column: Clean & Direct Results */}
          <div className="lg:col-span-6 space-y-6">
            {/* 1. Prominent Primary CLV Card */}
            <div className="bg-slate-950 text-white rounded-3xl p-5 sm:p-8 shadow-xl relative overflow-hidden border border-slate-800">
              <div>
                <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">
                  Customer Lifetime Value (CLV)
                </span>
                <div className="text-4xl sm:text-5xl md:text-6xl font-black text-white mt-2 tracking-tight break-words">
                  {results.clv.toFixed(2)} €
                </div>
                <p className="text-xs text-slate-400 mt-2">
                  Tatsächlicher Kundenwert (Deckungsbeitrag bei {grossMarginPercent}% Marge) über {customerLifespan} Jahre.
                </p>
              </div>

              {/* 3 Essential Supporting Metrics */}
              <div className="mt-6 pt-6 border-t border-slate-800 grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="p-3 bg-slate-900 rounded-2xl">
                  <span className="text-[11px] text-slate-400 block">Gesamtumsatz:</span>
                  <span className="text-base sm:text-lg font-black text-white mt-0.5 block">
                    {results.lifetimeRevenue.toFixed(2)} €
                  </span>
                  <span className="text-[10px] text-slate-500 block">über {customerLifespan} J.</span>
                </div>

                <div className="p-3 bg-slate-900 rounded-2xl">
                  <span className="text-[11px] text-slate-400 block">Reingewinn (nach CAC):</span>
                  <span
                    className={`text-base sm:text-lg font-black mt-0.5 block ${
                      results.netProfitPerCustomer >= 0 ? "text-emerald-400" : "text-red-400"
                    }`}
                  >
                    {results.netProfitPerCustomer >= 0 ? "+" : ""}
                    {results.netProfitPerCustomer.toFixed(2)} €
                  </span>
                  <span className="text-[10px] text-slate-500 block">abzgl. {cac} € CAC</span>
                </div>

                <div className="p-3 bg-slate-900 rounded-2xl">
                  <span className="text-[11px] text-slate-400 block">Bestellungen:</span>
                  <span className="text-base sm:text-lg font-black text-white mt-0.5 block">
                    {results.totalOrders.toFixed(1)}x
                  </span>
                  <span className="text-[10px] text-slate-500 block">pro Kunde</span>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="mt-6 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
                <button
                  onClick={handleCopySummary}
                  className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold flex items-center justify-center gap-2 transition-colors cursor-pointer"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? "Kopiert!" : "Ergebnis kopieren"}</span>
                </button>
                <button
                  onClick={onOpenBooking}
                  className="px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold flex items-center justify-center gap-1.5 transition-colors cursor-pointer"
                >
                  <span>Marge mit Procware steigern</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            {/* 2. Payback Period & Amortisation (Below the main box) */}
            <div className="bg-white border border-slate-200 rounded-3xl p-5 sm:p-6 shadow-xs">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                    <Clock className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="text-sm font-extrabold text-slate-900">
                      Wann rentiert sich ein Neukunde? (Break-Even)
                    </h3>
                    <p className="text-[11px] text-slate-500">
                      Amortisation deiner Werbekosten (CAC)
                    </p>
                  </div>
                </div>
                <span
                  className={`text-xs font-black px-2.5 py-1 rounded-full border self-start sm:self-auto ${
                    results.isFirstOrderProfitable
                      ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                      : "bg-blue-50 text-blue-700 border-blue-200"
                  }`}
                >
                  {results.isFirstOrderProfitable
                    ? "Sofort bei Order 1"
                    : `Nach ~${results.paybackMonths} Monaten`}
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs mb-4">
                <div className="p-3 bg-slate-50 rounded-2xl border border-slate-100">
                  <span className="text-slate-500 block">Deckungsbeitrag Order 1:</span>
                  <span className="text-base font-black text-slate-950 mt-0.5 block">
                    {results.profitPerOrder.toFixed(2)} €
                  </span>
                  <span className="text-[10px] text-slate-400">
                    bei {aov} € AOV & {grossMarginPercent}% Marge
                  </span>
                </div>
                <div className="p-3 bg-slate-50 rounded-2xl border border-slate-100">
                  <span className="text-slate-500 block">Werbekosten (CAC):</span>
                  <span className="text-base font-black text-slate-950 mt-0.5 block">
                    {cac.toFixed(2)} €
                  </span>
                  <span className="text-[10px] text-slate-400">zur Neukundengewinnung</span>
                </div>
              </div>

              {results.isFirstOrderProfitable ? (
                <div className="p-3.5 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs flex items-start gap-2.5">
                  <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold block">Direkt ab Bestellung 1 profitabel!</span>
                    Du verdienst bereits bei der ersten Bestellung netto{" "}
                    <strong>+{(results.profitPerOrder - cac).toFixed(2)} €</strong>. Jede weitere Nachbestellung ist reiner Zusatzgewinn.
                  </div>
                </div>
              ) : (
                <div className="p-3.5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 text-xs flex items-start gap-2.5">
                  <AlertCircle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold block">
                      Vorfinanzierung nötig ({results.ordersToBreakEven} Bestellungen)
                    </span>
                    Beim Erstkauf entsteht rechnerisch ein Minus von{" "}
                    <strong>{(results.profitPerOrder - cac).toFixed(2)} €</strong>. Der Kunde wird erst ab der {results.ordersToBreakEven}. Bestellung rentabel.
                  </div>
                </div>
              )}
            </div>

            {/* 3. Year-by-Year Cumulative Table */}
            <div className="bg-white border border-slate-200 rounded-3xl p-5 sm:p-6 shadow-xs">
              <h3 className="text-sm font-extrabold text-slate-900 mb-3">
                Entwicklung über die Jahre (pro Kunde)
              </h3>
              <div className="overflow-x-auto -mx-2 px-2 sm:mx-0 sm:px-0">
                <table className="w-full min-w-[420px] text-left text-xs">
                  <thead>
                    <tr className="border-b border-slate-100 text-slate-400 font-bold">
                      <th className="py-2">Jahr</th>
                      <th className="py-2">Bestellungen</th>
                      <th className="py-2">Umsatz</th>
                      <th className="py-2">Deckungsbeitrag</th>
                      <th className="py-2 text-right">Reingewinn (nach CAC)</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 text-slate-700 font-medium">
                    {results.yearlyBreakdown.map((row) => (
                      <tr key={row.year} className="hover:bg-slate-50">
                        <td className="py-2.5 font-bold text-slate-900">Jahr {row.year}</td>
                        <td className="py-2.5">{row.orders}x</td>
                        <td className="py-2.5">{row.revenue} €</td>
                        <td className="py-2.5">{row.grossProfit} €</td>
                        <td
                          className={`py-2.5 text-right font-black ${
                            row.netProfit >= 0 ? "text-emerald-600" : "text-red-500"
                          }`}
                        >
                          {row.netProfit >= 0 ? "+" : ""}
                          {row.netProfit} €
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Procware Margin Lever */}
            <div className="p-5 rounded-3xl bg-gradient-to-br from-slate-900 to-blue-950 border border-blue-800/80 text-white space-y-3 shadow-xs">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-blue-400 shrink-0" />
                <span className="text-xs font-bold text-blue-300">
                  {currentLang === "en" ? "Procware Margin Impact:" : "Marge steigern mit Procware:"}
                </span>
              </div>
              <h4 className="text-sm font-bold text-white">
                {currentLang === "en"
                  ? "Factory-direct sourcing increases your margins by 20% to 40%"
                  : "Wer bei Procware sourct, erhöht seine Marge im Schnitt um 20% bis 40%"}
              </h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                {currentLang === "en"
                  ? "Customer Lifetime Value scales directly with gross margin. Procware gives you factory-direct pricing without distributor markups, maximizing profit retention on every recurring order."
                  : "Dein Customer Lifetime Value skaliert direkt mit deiner Bruttomarge. Wer bei Procware sourct, erhöht seine Marge um 20% bis 40% – dadurch bleibt bei jeder einzelnen Nachbestellung spürbar mehr Reingewinn für dein Wachstum übrig."}
              </p>
              <div className="pt-2 flex flex-wrap items-center justify-between gap-3">
                <button
                  onClick={handleCopySummary}
                  className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? (currentLang === "en" ? "Copied!" : "Kopiert!") : (currentLang === "en" ? "Copy Results" : "Ergebnis kopieren")}</span>
                </button>
                <a
                  href="https://calendly.com/team-procware/new-meeting"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer"
                >
                  <span>{currentLang === "en" ? "Boost Margins with Procware" : "Marge mit Procware hebeln"}</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Educational & SEO Content Section */}
      <section className="py-12 bg-slate-50 border-t border-slate-200">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
          {/* Formula Explanation */}
          <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-xs">
            <h2 className="text-2xl font-black text-slate-950 mb-4">
              Wie berechnet sich der Customer Lifetime Value (CLV)?
            </h2>
            <p className="text-sm text-slate-600 leading-relaxed font-normal mb-6">
              Der <strong>Customer Lifetime Value (CLV)</strong> zeigt dir, wie viel ein Kunde während seiner gesamten Geschäftsbeziehung zu deinem Store einbringt:
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200">
                <div className="text-xs font-bold uppercase text-slate-500 mb-1">1. Gesamtumsatz</div>
                <div className="font-mono text-sm font-bold text-slate-900 bg-white p-3 rounded-xl border border-slate-200">
                  Umsatz = AOV × Bestellungen pro Jahr × Jahre
                </div>
              </div>
              <div className="p-4 rounded-2xl bg-blue-50/60 border border-blue-200">
                <div className="text-xs font-bold uppercase text-blue-700 mb-1">2. Tatsächlicher Wert (CLV)</div>
                <div className="font-mono text-sm font-bold text-blue-950 bg-white p-3 rounded-xl border border-blue-200">
                  CLV = Gesamtumsatz × Bruttomarge %
                </div>
              </div>
            </div>
          </div>

          {/* 4 Levers to Increase CLV on Shopify */}
          <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-xs">
            <h2 className="text-2xl font-black text-slate-950 mb-6">
              Die 4 Hebel zur Steigerung deines Customer Lifetime Value
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="flex gap-4">
                <div className="w-10 h-10 rounded-2xl bg-blue-50 flex items-center justify-center text-blue-600 font-black shrink-0">
                  1
                </div>
                <div>
                  <h3 className="font-bold text-slate-950 text-base">Warenkorbwert erhöhen (AOV)</h3>
                  <p className="text-xs text-slate-600 mt-1 leading-relaxed">
                    Setze auf Bundle-Angebote, Mengenstaffeln und gezielte Upsells im Shopify Checkout.
                  </p>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="w-10 h-10 rounded-2xl bg-blue-50 flex items-center justify-center text-blue-600 font-black shrink-0">
                  2
                </div>
                <div>
                  <h3 className="font-bold text-slate-950 text-base">Wiederkaufsrate steigern</h3>
                  <p className="text-xs text-slate-600 mt-1 leading-relaxed">
                    Reaktiviere Bestandskunden mit automatisierten E-Mail-Flows (z. B. Nachbestell-Erinnerungen oder VIP-Rabatte).
                  </p>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="w-10 h-10 rounded-2xl bg-blue-50 flex items-center justify-center text-blue-600 font-black shrink-0">
                  3
                </div>
                <div>
                  <h3 className="font-bold text-slate-950 text-base">Wareneinsatz & Sourcing optimieren</h3>
                  <p className="text-xs text-slate-600 mt-1 leading-relaxed">
                    Jeder Prozentpunkt mehr Marge fließt 1:1 in deinen Gewinn. Über <strong>Procware Sourcing</strong> erzielst du direkte Fabrikpreise ohne Zwischenhändler.
                  </p>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="w-10 h-10 rounded-2xl bg-blue-50 flex items-center justify-center text-blue-600 font-black shrink-0">
                  4
                </div>
                <div>
                  <h3 className="font-bold text-slate-950 text-base">Schnelles Fulfillment</h3>
                  <p className="text-xs text-slate-600 mt-1 leading-relaxed">
                    Kunden mit schneller Lieferzeit (1–3 Tage) und hochwertiger Verpackung bestellen nachweislich deutlich häufiger wieder.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* FAQ Accordion */}
          <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-xs">
            <h2 className="text-2xl font-black text-slate-950 mb-6">
              Häufige Fragen (FAQ)
            </h2>
            <div className="space-y-4">
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80">
                <h3 className="text-sm font-bold text-slate-900">
                  Warum ist der Deckungsbeitrag wichtiger als der reine Umsatz?
                </h3>
                <p className="text-xs text-slate-600 mt-1.5 leading-relaxed">
                  Ein Kunde mit 200 € Umsatz bei nur 20% Marge bringt dir 40 € Ertrag. Betragen deine Werbekosten (CAC) 45 €, machst du trotz 200 € Umsatz Verlust. Daher berechnen wir den CLV immer auf Basis deiner echten Bruttomarge.
                </p>
              </div>
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80">
                <h3 className="text-sm font-bold text-slate-900">
                  Woher bekomme ich die Zahlen in Shopify?
                </h3>
                <p className="text-xs text-slate-600 mt-1.5 leading-relaxed">
                  Im Shopify Admin unter <em>Analytics → Berichte → Kunden</em> findest du den durchschnittlichen Bestellwert (AOV) sowie die Wiederkaufrate (Returning Customer Rate).
                </p>
              </div>
            </div>
          </div>

          {/* Bottom Procware CTA */}
          <div className="p-8 rounded-3xl bg-slate-950 text-white flex flex-col md:flex-row items-center justify-between gap-6">
            <div>
              <h3 className="text-xl font-black text-white">
                Möchtest du deinen Kundenwert und deine Marge nachhaltig steigern?
              </h3>
              <p className="text-xs text-slate-400 mt-1 max-w-xl">
                Mit Procware senkst du deine Produkt- und Frachtkosten ab der ersten Bestellung und steigerst deine
                Wiederkaufrate durch zuverlässiges Express-Fulfillment.
              </p>
            </div>
            <button
              onClick={onOpenBooking}
              className="px-6 py-3 rounded-2xl bg-blue-600 hover:bg-blue-500 font-extrabold text-sm text-white shrink-0 flex items-center gap-2 transition-colors cursor-pointer"
            >
              <Calendar className="w-4 h-4" />
              <span>Strategiegespräch buchen</span>
            </button>
          </div>
        </div>
      </section>
    </div>
  );
};
